#!/bin/bash

home="jeiltrx.co.kr"
dblogin="jeiltrx"
dbname="jeiltrx"
trgtsrvr="119.207.79.150"
date=$(date +%Y%m%d)

#create tranfer file
if touch /home/$home/exprt_$home
	then
		echo -e "\e[34mTransfer /home/$home/exprt_$home created\e[0m"
	else
		echo "Cant create transfer file, exit script"
		exit 0
fi
echo


#searching for users of this hompage

echo -e "\e[34m$home users\e[0m"
echo
mailusrs=$( cat /etc/passwd | grep $home | cut -d ':' -f1 )
echo $mailusrs >> /home/$home/mailuserslist$date

for i in $(echo $mailusrs)
do
cat /etc/shadow | grep $i  >> /home/$home/exprt_$home
done

echo $mailusrs
echo
echo -e "\e[34mUsers saved in /home/$home/mailuserslist$date\e[0m"
echo


#brake

echo -n "Make users on $trgtsrvr. When users done press y, or press n to exit script: "

read ans
case "$ans" in
	y|Y) echo "Great, here we go"
	;;
	n|N) echo "Before exit script press y if you want to delete a file created by the script."
	echo $(rm /home/$home/mailuserslist$date /home/$home/exprt_$home)
	exit 0
	;;
#	*) echo "One more time: y or n"
#	;;
esac
echo

#making mysql dump
case "$db" in
	y|Y)echo "MYSQL Password:"
	if mysqldump -u root -p $dbname > /home/$home/$dbname$date.sql
		then
		echo "Database was copied in /home/$home/$dbname$date.sql" >> /home/$home/exprt_$home
		else
		echo "Its some problems here, try by hands"
	fi
	;;
	n|N) echo "You choosed "no database" for this hompage"
	;;
	*) echo "Wrong parametr in parametr db. Databasr didnt copyed."
	;;
esac

#Write virtualhost parametrs in transfer file
echo -e "\e[34mCopying virtualhost.conf settings for $home\e[0m"

echo -e "\e[31mHERE IS ALL WHAT $home HAVE IN APACHE CONFIGURATIONS. CHECK IT!\e[0m"
cd /usr/local/apache/conf
grep -rni -C2 "$home" *
cd
echo

echo "input CBandLimit "
read cdlim

#echo -e "\e[31mHERE IS WHAT I COPYED.\e[0m"
#echo "<VirtualHost $trgtsrvr:80>"
#sed -n "/${home}/p" /usr/local/apache/conf/virtualhost.conf
#echo "CBandLimit $cdlim"
#echo "CBandPeriod 1D"
#echo "</VirtualHost>"

echo "<VirtualHost $trgtsrvr:80>" >> /home/$home/exprt_$home
sed -n "/${home}/p" /usr/local/apache/conf/virtualhost.conf >> /home/$home/exprt_$home
sed -e '/Directory/d'; '/Transfer/d'; '/Limit/d' /home/$home/exprt_$home
echo "CBandLimit $cdlim" >> /home/$home/exprt_$home
echo "CBandPeriod 1D" >> /home/$home/exprt_$home
echo "</VirtualHost>" >> /home/$home/exprt_$home
echo

echo -e "\e[31mHERE IS WHAT I COPYED.\e[0m"

sed -n '/VirtualHost/,$p' /home/$home/exprt_$home

#cheking virtustable and local-host-name
echo -e "\e[31mvirtustable settings\e[0m"
cat /etc/mail/virtusertable | grep $home
echo
echo "virtustable settings" >> /home/$home/exprt_$home
cat /etc/mail/virtusertable | grep $home >> /home/$home/exprt_$home

echo -e "\e[31mlocal-host-name settings\e[0m"
cat /etc/mail/local-host-names | grep $home
cat /etc/mail/local-host-names | grep $home >> /home/$home/exprt_$home
echo

#cheking size of hompage directory
echo -e "\e[34mFolder size $(du -sh /home/$home/)\e[0m"
echo

#RSYN Part
echo -e "\e[31mShould I rsync this folder to server $trgtsrvr? Choose y or n:\e[0m"
read rsans
case "$rsans" in
	y|Y) rsync -avr /home/$home/ $trgtsrvr::home/$home/
	;;
	n|N) echo "Exit script"
	exit
	;;
        *) echo "Exit script"
	exit 0
        ;;
esac


#RSYNK MAIL
echo -e "\e[31mrsync user's mail folders to server $trgtsrvr? Choose y or n:\e[0m"

read mailrs
case "$mailrs" in
        y|Y) for x in $mailusrs ; do  rsync -avr /var/spool/mail/$x $trgtsrvr::var/spool/mail/$x ; done 
	;;
        n|N) echo "Exit script"
	exit
	;;
esac

